test2

SELECT MEMBER_ID,FIRST_NAME,LAST_NAME,COUNT(DISTINCT CONDITION_CD) FROM
(SELECT PRODUCT_NAME,MEMBER_ID,LAST_NAME,FIRST_NAME,MIDDLE_INIT,GENDER,DOB,AGE,SUBSCRIBER_ID,COVERAGE_START_DT,COVERAGE_END_DT,EMPLOYER_NAME,CONDITION_CD,IDENTIFIED_DATE,
CASE WHEN PAYLOAD LIKE '%HQ%' THEN 'Y' ELSE 'N' END AS HEALTH_QUESTION FROM HMQAT01.USER_CONDITIONS_VW WHERE CONDITION_NAME IN ('Diabetes','Coronary Artery Disease') 
AND IDENTIFIED_DATE BETWEEN '27-JUL-2013' AND '27-JUL-2015' order by member_id)
GROUP BY MEMBER_ID,FIRST_NAME,LAST_NAME ORDER BY COUNT(DISTINCT CONDITION_CD) DESC,LAST_NAME;


