SELECT MEMBER_ID,FIRST_NAME,LAST_NAME,COUNT(DISTINCT CONDITION_CD) FROM
(SELECT PRODUCT_NAME,MEMBER_ID,LAST_NAME,FIRST_NAME,MIDDLE_INIT,GENDER,DOB,AGE,SUBSCRIBER_ID,COVERAGE_START_DT,COVERAGE_END_DT,EMPLOYER_NAME,CONDITION_CD,IDENTIFIED_DATE,
CASE WHEN PAYLOAD LIKE '%HQ%' THEN 'Y' ELSE 'N' END AS HEALTH_QUESTION FROM HMQAT01.USER_CONDITIONS_VW WHERE CONDITION_NAME IN ('Diabetes','Coronary Artery Disease') 
AND IDENTIFIED_DATE BETWEEN '27-JUL-2013' AND '27-JUL-2015' order by member_id)
GROUP BY MEMBER_ID,FIRST_NAME,LAST_NAME ORDER BY COUNT(DISTINCT CONDITION_CD) DESC,LAST_NAME;



SELECT PRODUCT_NAME,MEMBER_ID,LAST_NAME,FIRST_NAME,MIDDLE_INIT,GENDER,DOB,AGE,SUBSCRIBER_ID,COVERAGE_START_DT,COVERAGE_END_DT,EMPLOYER_NAME,CONDITION_CD,IDENTIFIED_DATE,
CASE WHEN PAYLOAD LIKE '%HQ%' THEN 'Y' ELSE 'N' END AS HEALTH_QUESTION FROM HMQAT01.USER_CONDITIONS_VW WHERE CONDITION_NAME IN ('Diabetes','Coronary Artery Disease') 
AND IDENTIFIED_DATE BETWEEN '27-JUL-2013' AND '27-JUL-2015' order by member_pk ;

SELECT DISTINCT USER_PK,MEMBER_PK,MEMBER_ID,FIRST_NAME,LAST_NAME,COUNT(DISTINCT CONDITION_CD) FROM
(SELECT * FROM HMQAT01.USER_CONDITIONS_VW WHERE CONDITION_NAME IN ('Coronary Artery Disease','Asthma','Diabetes','Hyperlipidemia','Hypertension','Tobacco Usage') 
AND IDENTIFIED_DATE BETWEEN '27-JUN-2015' AND '27-JUL-2015' AND MEMBER_PK=203704)
GROUP BY USER_PK,MEMBER_PK,MEMBER_ID,FIRST_NAME,LAST_NAME;

SELECT vw.*,CASE WHEN vw.PAYLOAD LIKE '%HQ%' THEN 'Y' ELSE 'N' END AS HEALTH_QUESTION FROM HMQAT01.USER_CONDITIONS_VW vw WHERE MEMBER_ID IN (057265400);